###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /feegow
        volumes:
            - '.:/feegow'
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=feegow
            - MYSQL_USER=webmaster
            - MYSQL_PASSWORD=segredo
        ports:
            - '26002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /feegow
        volumes:
            - '.:/feegow'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '26000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /feegow
        volumes:
            - '.:/feegow'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
